//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sincDelivery.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obavjestenje
    {
        public int ID { get; set; }
        public string Tekst { get; set; }
        public string Lokacija { get; set; }
        public string Naslov { get; set; }
        public Nullable<bool> Aktivan { get; set; }
        public Nullable<System.DateTime> DatumIVrijemeKreiranja { get; set; }
        public string IzdaoObavjestenjeID { get; set; }
        public Nullable<int> VozacID { get; set; }
        public Nullable<int> NalogID { get; set; }
        public string PlaceID { get; set; }
    }
}
