//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sincDelivery.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PutniNalogStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PutniNalogStatu()
        {
            this.PutniNalogs = new HashSet<PutniNalog>();
            this.PutniNalogs1 = new HashSet<PutniNalog>();
        }
    
        public int ID { get; set; }
        public string Naziv { get; set; }
        public Nullable<bool> Aktivan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PutniNalog> PutniNalogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PutniNalog> PutniNalogs1 { get; set; }
    }
}
