//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sincDelivery.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PutniNalog
    {
        public int ID { get; set; }
        public string Sifra { get; set; }
        public Nullable<int> VoziloID { get; set; }
        public Nullable<int> VozacID { get; set; }
        public Nullable<int> PocetnaKilometraza { get; set; }
        public Nullable<int> KrajnjaKilometraza { get; set; }
        public Nullable<double> PotrosenoGoriva { get; set; }
        public Nullable<int> ZaposlenikIzdaoID { get; set; }
        public Nullable<int> ZaposlenikZakljucioID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> DatumIVrijemeIzdavanja { get; set; }
        public Nullable<System.DateTime> DatumIVrijemeZakljucivanja { get; set; }
        public Nullable<System.DateTime> DatumIVrijemePolaska { get; set; }
        public Nullable<System.DateTime> DatumIVrijemeDolaska { get; set; }
        public Nullable<bool> Zavrseno { get; set; }
        public Nullable<double> Norma { get; set; }
        public Nullable<bool> Aktivan { get; set; }
        public string LokacijaPolazak { get; set; }
        public string LokacijaOdrediste { get; set; }
    
        public virtual PutniNalogStatu PutniNalogStatu { get; set; }
        public virtual PutniNalogStatu PutniNalogStatu1 { get; set; }
        public virtual Vozilo Vozilo { get; set; }
        public virtual Vozilo Vozilo1 { get; set; }
    }
}
