//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sincDelivery.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sincDeliveryEntities : DbContext
    {
        public sincDeliveryEntities()
            : base("name=sincDeliveryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<KorisnikTip> KorisnikTips { get; set; }
        public virtual DbSet<PutniNalog> PutniNalogs { get; set; }
        public virtual DbSet<PutniNalogStatu> PutniNalogStatus { get; set; }
        public virtual DbSet<Vozilo> Voziloes { get; set; }
        public virtual DbSet<VoziloMarka> VoziloMarkas { get; set; }
        public virtual DbSet<VoziloMarkaTip> VoziloMarkaTips { get; set; }
        public virtual DbSet<VoziloStatu> VoziloStatus { get; set; }
        public virtual DbSet<VoziloTip> VoziloTips { get; set; }
        public virtual DbSet<Obavjestenje> Obavjestenjes { get; set; }
    }
}
