//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sincDelivery.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozilo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vozilo()
        {
            this.PutniNalogs = new HashSet<PutniNalog>();
            this.PutniNalogs1 = new HashSet<PutniNalog>();
        }
    
        public int ID { get; set; }
        public string Naziv { get; set; }
        public string GarazniBroj { get; set; }
        public string RegistarskiBroj { get; set; }
        public string BrojSasije { get; set; }
        public Nullable<int> Kilometraza { get; set; }
        public Nullable<int> MarkaVozilaID { get; set; }
        public Nullable<int> TipVozilaID { get; set; }
        public Nullable<int> StatusVozilaID { get; set; }
        public Nullable<double> ProsjecnaPotrosnja { get; set; }
        public Nullable<double> TrenutnaLokacijaX { get; set; }
        public Nullable<double> TrenutnaLokacijaY { get; set; }
        public Nullable<bool> Aktivan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PutniNalog> PutniNalogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PutniNalog> PutniNalogs1 { get; set; }
        public virtual VoziloMarka VoziloMarka { get; set; }
        public virtual VoziloStatu VoziloStatu { get; set; }
        public virtual VoziloTip VoziloTip { get; set; }
    }
}
